"""Gradio demo for Ouroboros.

Paste a document, get back the character-aligned authorship segmentation the
model produces: per-token provenance decoded through the CRF, the document
verdict under the report's Section 5.1 rule, the class fractions, and the
four-way humanization probe.

The "Why?" section explains the prediction: word attributions from the
gradient of an AI score with respect to the input embeddings (Gradient x Input
or Integrated Gradients), and sentence occlusion (re-score without each sentence).
"""

from __future__ import annotations

import argparse
import html
import os
import time
from collections import defaultdict
from pathlib import Path

import gradio as gr
import numpy as np
import pandas as pd
import torch

from ouroboros.infer.extract import SUPPORTED, extract_text, normalize_layout, unwrap
from ouroboros.infer.explain import (
    sentence_occlusion,
    token_attributions,
    word_occlusion,
    words_from_tokens,
)
from ouroboros.infer.postprocess import postprocess
from ouroboros.infer.predict import Predictor
from ouroboros.labels import BUCKET_CENTERS

# --------------------------------------------------------------------------
# presentation
# --------------------------------------------------------------------------
LABEL_STYLE = {
    "human": "#2e7d32",
    "ai-assisted": "#ef6c00",
    "ai-generated": "#c62828",
}

VERDICT_BLURB = {
    "human": "Written by a human (or with negligible AI involvement).",
    "mixed": "Mixed authorship — neither threshold is met.",
    "ai": "Generated by an AI.",
}

MIN_WORDS = 50  # report Section 3.1: below this there is not enough signal


class DemoState:
    """Lazily loads the predictor so the UI starts instantly."""

    def __init__(self, run_dir: str, device: str):
        self.run_dir = run_dir
        self.device = device
        self._predictor: Predictor | None = None

    @property
    def predictor(self) -> Predictor:
        if self._predictor is None:
            self._predictor = Predictor.from_run(self.run_dir, device=self.device)
        return self._predictor

    @property
    def calibrated(self) -> bool:
        return not self.predictor.calibrator.identity


# --------------------------------------------------------------------------
# heatmap rendering
# --------------------------------------------------------------------------
AI_RGB = "198, 40, 40"  # matches LABEL_STYLE["ai-generated"]
HUMAN_RGB = "46, 125, 50"  # matches LABEL_STYLE["human"]


def render_heatmap(text: str, spans: list[tuple[int, int, float, str]]) -> str:
    """Inline heatmap. ``spans`` are ``(start, end, value in [-1, 1], tooltip)``;
    positive values are tinted towards AI (red), negative towards human (green)."""
    parts, cursor = [], 0
    for start, end, value, tip in sorted(spans):
        if start < cursor:
            continue
        parts.append(html.escape(text[cursor:start]))
        value = float(np.clip(value, -1.0, 1.0))
        rgb = AI_RGB if value > 0 else HUMAN_RGB
        alpha = 0.85 * abs(value)
        parts.append(
            f'<span title="{html.escape(tip)}" style="background: rgba({rgb}, {alpha:.3f}); '
            f'border-radius: 3px; padding: 0 1px;">{html.escape(text[start:end])}</span>'
        )
        cursor = end
    parts.append(html.escape(text[cursor:]))
    return (
        '<div style="white-space: pre-wrap; line-height: 1.9; font-size: 15px; '
        'padding: 12px; border: 1px solid rgba(128,128,128,.3); border-radius: 8px;">'
        + "".join(parts)
        + "</div>"
    )


def heatmap_legend(left: str, right: str) -> str:
    return (
        '<div style="display:flex; align-items:center; gap:8px; font-size:13px; margin:4px 0;">'
        f"<span>{left}</span>"
        f'<span style="flex:0 0 220px; height:12px; border-radius:6px; background: linear-gradient('
        f'90deg, rgba({HUMAN_RGB},.85), rgba(128,128,128,.08), rgba({AI_RGB},.85));"></span>'
        f"<span>{right}</span></div>"
    )


def token_heatmap(text: str, offsets, token_logits: np.ndarray) -> str:
    """Per-word AI probability from the token head, before calibration and CRF."""
    logits = token_logits - token_logits.max(1, keepdims=True)
    probs = np.exp(logits) / np.exp(logits).sum(1, keepdims=True)
    p_ai = probs[:, 2] + 0.5 * probs[:, 1]  # weighted like f_AI
    words = words_from_tokens(text, offsets, p_ai, reduce="mean")
    spans = [
        (w.start, w.end, 2.0 * w.score - 1.0, f"p_AI = {w.score:.2f}") for w in words
    ]
    return heatmap_legend("human (p=0)", "AI (p=1)") + render_heatmap(text, spans)


NORM_FULL = "Full (re-join lines + rebuild paragraphs)"
NORM_UNWRAP = "Re-join hard-wrapped lines only"
NORM_NONE = "None (raw text)"


def prepare(text: str, normalize) -> tuple[str, bool]:
    """Text actually scored under the chosen layout normalization."""
    text = (text or "").strip()
    if not text or normalize in (False, None, NORM_NONE):
        return text, False
    canonical = unwrap(text) if normalize == NORM_UNWRAP else normalize_layout(text)
    return canonical, canonical != text


def analyse(text: str, state: DemoState, normalize=NORM_FULL):
    text, changed = prepare(text, normalize)
    if not text:
        return [], {}, "", {}, [], "Paste some text first.", "", None

    words = len(text.split())
    notes: list[str] = []
    if changed:
        notes.append(
            "ℹ️ Layout normalized before scoring: hard-wrapped lines re-joined and "
            "paragraphs rebuilt (one line per paragraph, blank line between). The model "
            "picked up layout cues during training that are not authorship; this removes "
            "them. Pick *None* under *Layout normalization* to score the raw text."
        )
    if words < MIN_WORDS:
        notes.append(
            f"⚠️ {words} words. The paper scopes detection to documents of at least "
            f"{MIN_WORDS} words — below that there is not enough signal, so treat this "
            "result as unreliable."
        )

    started = time.time()
    predictor = state.predictor
    agg, obs = predictor.observe(text)
    prediction = postprocess(agg, predictor.calibrator, predictor.cfg.postprocess)
    humanizer = predictor.humanizer(text)
    elapsed = time.time() - started

    # gr.HighlightedText wants (substring, label) pairs covering the document.
    highlighted = [
        (text[segment.start : segment.end], segment.label_name)
        for segment in prediction.segments
        if segment.end > segment.start
    ]

    verdict = prediction.document_label
    verdict_label = {
        "human": prediction.fractions["human"],
        "ai-assisted": prediction.fractions["ai-assisted"],
        "ai-generated": prediction.fractions["ai-generated"],
    }

    summary = (
        f"### {verdict.upper()} — weighted AI fraction **{prediction.weighted_ai_fraction:.3f}**\n\n"
        f"{VERDICT_BLURB[verdict]}\n\n"
        f"Decision rule: `human` if f_human ≥ 0.90, `ai` if f_AI ≥ 0.80, else `mixed`.\n\n"
        f"<sub>{len(prediction.segments)} segment(s) · {words} words · {elapsed:.2f}s</sub>"
    )

    rows = []
    for i, segment in enumerate(prediction.segments, 1):
        excerpt = text[segment.start : segment.end].replace("\n", " ").strip()
        if len(excerpt) > 110:
            excerpt = excerpt[:107] + "…"
        rows.append(
            [
                i,
                segment.label_name,
                f"{segment.confidence:.3f}",
                f"{segment.start}–{segment.end}",
                segment.end - segment.start,
                excerpt,
            ]
        )

    if not state.calibrated:
        notes.append(
            "⚠️ No calibrator found in the run directory — falling back to raw token "
            "logits. Run `ouroboros calibrate` for properly calibrated output."
        )
    note_text = "\n\n".join(notes)

    heat = token_heatmap(text, agg.offsets, agg.features[:, :3])
    lengths = np.array([w.hi - w.lo for w in obs.windows], dtype=np.float64)
    buckets = np.average(
        np.stack([w.segment_probs for w in obs.windows]), axis=0, weights=lengths
    )
    bucket_df = pd.DataFrame(
        {"f_AI bucket": [f"{c:.2f}" for c in BUCKET_CENTERS], "probability": buckets}
    )

    return highlighted, verdict_label, summary, humanizer, rows, note_text, heat, bucket_df


# --------------------------------------------------------------------------
# "why?" -- attributions
# --------------------------------------------------------------------------
METHOD_CHOICES = {
    "Word occlusion (most readable)": "word_occlusion",
    "Integrated Gradients": "integrated_gradients",
    "Gradient × Input (fastest)": "gradxinput",
}
TARGET_CHOICES = {
    "Token head — tokens flagged AI only": "flagged",
    "Token head — mean AI log-odds (whole text)": "token",
    "Segment head — log-odds f_AI > 0.5": "document",
}


def _top_words(words, k: int = 15) -> tuple[list[list], list[list]]:
    """Mean attribution per (lower-cased) word type, top-k each direction.

    The mean per occurrence, not the sum, so frequent function words and
    punctuation do not crowd out the rarer words that actually carry style.
    """
    totals: dict[str, float] = defaultdict(float)
    counts: dict[str, int] = defaultdict(int)
    for w in words:
        key = w.text.lower()
        totals[key] += w.score
        counts[key] += 1
    means = {w: totals[w] / counts[w] for w in totals}
    ranked = sorted(means, key=means.get)
    to_ai = [[w, f"{means[w]:+.3f}", counts[w]] for w in reversed(ranked[-k:]) if means[w] > 0]
    to_human = [[w, f"{means[w]:+.3f}", counts[w]] for w in ranked[:k] if means[w] < 0]
    return to_ai, to_human


def explain(text: str, method_label: str, target_label: str, steps: int, occlude: bool, state):
    text = (text or "").strip()
    if not text:
        return "Paste some text first.", "", [], [], "", []
    method = METHOD_CHOICES[method_label]
    target = TARGET_CHOICES[target_label]
    predictor = state.predictor
    data_cfg = predictor.cfg.data

    started = time.time()
    token_mask, flagged_note = None, ""
    if target == "flagged" and method == "word_occlusion":
        target = "token"
        flagged_note = "whole text — word occlusion cannot restrict to flagged tokens"
    if target == "flagged":
        target = "token"
        labels = predictor.predict(text).token_labels
        if labels is not None and labels.any():
            token_mask = labels > 0  # ai-assisted or ai-generated after decoding
            flagged_note = f"restricted to the {int(token_mask.sum())} tokens labelled AI"
            if occlude:
                flagged_note += "; sentence occlusion scores the whole text"
        else:
            flagged_note = "no token labelled AI — explaining the whole text instead"
    try:
        if method == "word_occlusion":
            score, words = word_occlusion(
                predictor.model,
                predictor.tokenizer,
                text,
                data_cfg.window_tokens,
                data_cfg.stride_tokens,
                target=target,
                device=state.device,
            )
            values = np.array([w.score for w in words])
            n_units = f"{len(words)} words occluded"
        else:
            values, offsets, score = token_attributions(
                predictor.model,
                predictor.tokenizer,
                text,
                data_cfg.window_tokens,
                data_cfg.stride_tokens,
                target=target,
                method=method,
                steps=int(steps),
                device=state.device,
                token_mask=token_mask,
            )
            words = words_from_tokens(text, offsets, values)
            n_units = f"{len(offsets)} tokens"
    finally:
        torch.cuda.empty_cache()

    magnitudes = np.abs([w.score for w in words]) if words else np.zeros(1)
    # A robust scale: a handful of extreme tokens must not wash out the rest.
    scale = max(float(np.percentile(magnitudes, 95)), 1e-8)
    spans = [(w.start, w.end, w.score / scale, f"{w.score:+.4f}") for w in words]
    word_html = heatmap_legend("→ human", "→ AI") + render_heatmap(text, spans)
    to_ai, to_human = _top_words(words)

    sentence_html, sentence_rows, occlusion_note = "", [], ""
    if occlude:
        base, sentences = sentence_occlusion(
            predictor.model,
            predictor.tokenizer,
            text,
            data_cfg.window_tokens,
            data_cfg.stride_tokens,
            target=target,
            device=state.device,
        )
        if sentences:
            s_scale = max(max(abs(s.delta) for s in sentences), 1e-8)
            sentence_html = heatmap_legend("sentence pulls towards human", "sentence pushes towards AI") + render_heatmap(
                text, [(s.start, s.end, s.delta / s_scale, f"Δ = {s.delta:+.3f}") for s in sentences]
            )
            for s in sorted(sentences, key=lambda s: -abs(s.delta)):
                excerpt = s.text.replace("\n", " ").strip()
                if len(excerpt) > 140:
                    excerpt = excerpt[:137] + "…"
                sentence_rows.append([f"{s.delta:+.3f}", f"{base - s.delta:+.3f}", excerpt])
            occlusion_note = f" · occlusion over {len(sentences)} sentences (score {base:+.3f})"
        else:
            occlusion_note = " · occlusion needs at least two sentences"

    total = float(np.sum(values))
    total_note = (
        f"Sum of attributions: {total:+.3f}"
        + (
            " (Integrated Gradients: ≈ score(text) − score(zero embeddings) for a single window)"
            if method == "integrated_gradients"
            else ""
        )
        if method != "word_occlusion"
        else "Each word's value is score(text) − score(text without that word)."
    )
    summary = (
        f"**AI score** ({'token' if target == 'token' else 'segment'} head, log-odds"
        + (f"; {flagged_note}" if flagged_note else "")
        + "): "
        f"**{score:+.3f}** — positive leans AI, negative leans human.\n\n"
        + total_note
        + f"\n\n<sub>{n_units} · {time.time() - started:.1f}s{occlusion_note}</sub>"
    )
    return summary, word_html, to_ai, to_human, sentence_html, sentence_rows


EXAMPLES = [
    [
        "I went down there on Tuesday and honestly the guy behind the counter just "
        "shrugged at me when I asked about the warranty. My sister swears by the green "
        "model but I genuinely cannot tell the difference, and at that price I'd rather "
        "put the money towards something else. We ended up walking back in the rain "
        "because nobody had thought to bring a jacket, which pretty much summed up the "
        "whole afternoon. I'll probably go back, but not for a while."
    ],
    [
        "Furthermore, it is essential to understand that leveraging comprehensive "
        "frameworks facilitates significant organisational growth. Moreover, individuals "
        "should utilise various robust strategies to obtain optimal outcomes across "
        "numerous domains. In conclusion, the intricate landscape of this realm "
        "underscores several pivotal considerations that demonstrate the crucial "
        "importance of a holistic approach to delivering sustainable value for all "
        "stakeholders involved in the process."
    ],
    [
        "I went down there on Tuesday and the guy behind the counter just shrugged at me "
        "when I asked about the warranty. My sister swears by the green one but I can't "
        "tell the difference. Furthermore, it is essential to understand that leveraging "
        "comprehensive frameworks facilitates significant organisational growth. Moreover, "
        "individuals should utilise various robust strategies to obtain optimal outcomes. "
        "In conclusion, the intricate landscape of this realm underscores several pivotal "
        "considerations for all stakeholders."
    ],
]


def load_file(path: str | None) -> str:
    """Uploaded file -> the plain text shown in the box and analysed."""
    if not path:
        return ""
    try:
        return extract_text(path)
    except Exception as exc:  # shown to the user rather than crashing the app
        raise gr.Error(f"Could not read {Path(path).name}: {exc}")


def build_ui(state: DemoState) -> gr.Blocks:
    with gr.Blocks(title="Ouroboros — AI text detection", theme=gr.themes.Soft()) as ui:
        gr.Markdown(
            "# Ouroboros\n"
            "Token-level AI-text detection — an open reimplementation of "
            "**Pangram 4** ([arXiv:2607.27183](https://arxiv.org/abs/2607.27183)).\n\n"
            "The model labels **every token** as `human`, `ai-assisted` (co-written: human "
            "idea, AI wording) or `ai-generated`, then a linear-chain CRF turns those into "
            "clean, sentence-aligned segments."
        )

        with gr.Row():
            with gr.Column(scale=5):
                text_in = gr.Textbox(
                    label="Document",
                    placeholder="Paste at least 50 words…",
                    lines=16,
                )
                file_in = gr.File(
                    label="…or drop a file (PDF, DOCX, TXT, MD) — converted to plain text",
                    file_types=list(SUPPORTED),
                    type="filepath",
                    height=90,
                )
                with gr.Row():
                    run_btn = gr.Button("Analyse", variant="primary", scale=3)
                    clear_btn = gr.ClearButton(value="Clear", scale=1)
                norm_in = gr.Radio(
                    [NORM_FULL, NORM_UNWRAP, NORM_NONE],
                    value=NORM_FULL,
                    label="Layout normalization",
                    info="Full: on 800 test docs, false positives 0.75% → 4.25% on already-clean "
                    "text, but it fixes pasted PDF text. Re-join only: touches hard-wrapped text only.",
                )
                gr.Examples(
                    examples=EXAMPLES,
                    inputs=text_in,
                    label="Try: human · AI · spliced (human then AI)",
                )

            with gr.Column(scale=5):
                summary_md = gr.Markdown()
                notes_md = gr.Markdown()
                fractions = gr.Label(label="Character fractions by class", num_top_classes=3)
                humanizer = gr.Label(
                    label="Humanization probe (document level)", num_top_classes=4
                )

        gr.Markdown("### Segmentation")
        highlighted = gr.HighlightedText(
            label="Per-segment authorship",
            combine_adjacent=True,
            show_legend=True,
            color_map=LABEL_STYLE,
        )

        with gr.Tabs():
            with gr.Tab("Token probabilities"):
                gr.Markdown(
                    "What the token head believes about each word **before** calibration, "
                    "the CRF and sentence voting — the raw evidence the segmentation is "
                    "built from. Hover a word for its probability."
                )
                token_html = gr.HTML()
            with gr.Tab("Document AI-fraction distribution"):
                gr.Markdown(
                    "The segment head's distribution over the 15 buckets of the weighted "
                    "AI fraction (averaged over windows). Mass split between both ends "
                    "means the model sees two authors; mass in the middle means co-writing."
                )
                bucket_plot = gr.BarPlot(
                    x="f_AI bucket", y="probability", y_lim=[0, 1], height=260, sort=None
                )

        with gr.Accordion("Segment detail", open=False):
            table = gr.Dataframe(
                headers=["#", "label", "confidence", "chars", "length", "excerpt"],
                datatype=["number", "str", "str", "str", "number", "str"],
                wrap=True,
            )

        gr.Markdown(
            "<sub>Confidence is the mean CRF marginal over a segment's tokens: it measures "
            "how peaked the unconstrained posterior is, not the probability that the final "
            "constrained label is correct.</sub>"
        )

        gr.Markdown(
            "## Why? — explaining the prediction\n"
            "Each word is coloured by how much it pushed the **AI score** up (red) or "
            "down (green). *Word occlusion* re-scores the text with each word removed. "
            "*Gradient × Input* takes the derivative of the score with respect to each "
            "word's input embedding, times the embedding (one backward pass); "
            "*Integrated Gradients* averages that gradient along a path from an empty "
            "input. Gradients are cheap but noisy on an LLM backbone — cross-check them "
            "against occlusion. **Sentence occlusion** does the same per sentence."
        )
        with gr.Row():
            method_in = gr.Radio(
                list(METHOD_CHOICES), value=list(METHOD_CHOICES)[0], label="Method"
            )
            target_in = gr.Radio(
                list(TARGET_CHOICES), value=list(TARGET_CHOICES)[0], label="Score to explain"
            )
            with gr.Column():
                steps_in = gr.Slider(4, 64, value=16, step=4, label="IG steps")
                occlude_in = gr.Checkbox(value=True, label="Sentence occlusion")
        explain_btn = gr.Button("Explain", variant="secondary")
        explain_md = gr.Markdown()
        word_html = gr.HTML()
        with gr.Row():
            to_ai_table = gr.Dataframe(
                headers=["word", "mean attribution", "count"],
                datatype=["str", "str", "number"],
                label="Words pushing towards AI",
            )
            to_human_table = gr.Dataframe(
                headers=["word", "mean attribution", "count"],
                datatype=["str", "str", "number"],
                label="Words pushing towards human",
            )
        with gr.Accordion("Sentence occlusion", open=True):
            sentence_html = gr.HTML()
            sentence_table = gr.Dataframe(
                headers=["Δ score", "score without it", "sentence"],
                datatype=["str", "str", "str"],
                wrap=True,
            )
        gr.Markdown(
            "<sub>Attributions are local explanations of one differentiable score, not "
            "of the CRF decisions; subword attributions are summed per word. They show "
            "what the network *relies on*, which may be a style cue rather than a "
            "reason a human would accept.</sub>"
        )

        outputs = [
            highlighted, fractions, summary_md, humanizer, table, notes_md, token_html, bucket_plot
        ]
        run_btn.click(lambda t, n: analyse(t, state, n), inputs=[text_in, norm_in], outputs=outputs)
        text_in.submit(lambda t, n: analyse(t, state, n), inputs=[text_in, norm_in], outputs=outputs)
        file_in.upload(load_file, inputs=file_in, outputs=text_in).then(
            lambda t, n: analyse(t, state, n), inputs=[text_in, norm_in], outputs=outputs
        )
        explain_outputs = [
            explain_md, word_html, to_ai_table, to_human_table, sentence_html, sentence_table
        ]
        explain_btn.click(
            lambda t, n, *a: explain(prepare(t, n)[0], *a, state),
            inputs=[text_in, norm_in, method_in, target_in, steps_in, occlude_in],
            outputs=explain_outputs,
        )
        clear_btn.add([text_in, file_in, *outputs, *explain_outputs])

    return ui


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--run-dir",
        default=os.environ.get("OUROBOROS_RUN", "runs/stage2"),
        help="A released model directory / Hugging Face repo id, or a training run directory (checkpoint/ + config.yaml)",
    )
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--port", type=int, default=7860)
    parser.add_argument("--share", action="store_true", help="Create a public gradio link")
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    released = (run_dir / "ouroboros_config.yaml").exists() or not run_dir.exists()  # local release dir or hub id
    if not released and not (run_dir / "checkpoint").exists():
        raise SystemExit(
            f"no checkpoint in {run_dir}. Train first:\n"
            "  ouroboros train --config configs/stage1.yaml --stage2-config configs/stage2.yaml"
        )

    state = DemoState(str(run_dir), args.device)
    print(f"[demo] run dir: {run_dir}")
    build_ui(state).launch(server_port=args.port, share=args.share)


if __name__ == "__main__":
    main()
